image: node:latest

before_script:
  - yarn install

pages:
  cache:
    paths:
    - node_modules/
 
  stage: deploy
  script:
  - yarn run build
  - mv build public
  artifacts:
    paths:
    - public
  only:
  - master