image: node:latest

before_script:
  - yarn install

pages:
  cache:
    paths:
    - node_modules/
  variables:
    PUBLIC_URL: "https://kfrancois.gitlab.io/Todo-Reminder/"

  stage: deploy
  script:
  - yarn run build
  - mv build public
  artifacts:
    paths:
    - public
  only:
  - master